# Generated by Django 6.0.4 on 2026-04-28 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='HARMONY', max_length=200)),
                ('location', models.CharField(default='Nyali, Mombasa', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Premium 2 & 3 bedroom ensuite apartments with breathtaking ocean views', max_length=255)),
                ('about', models.TextField(blank=True)),
                ('bedrooms', models.CharField(blank=True, max_length=50)),
                ('size_range', models.CharField(blank=True, max_length=50)),
                ('ensuite', models.CharField(blank=True, max_length=50)),
                ('progress', models.PositiveIntegerField(default=65)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(default='harmony-nyali', unique=True)),
                ('amenities', models.ManyToManyField(blank=True, to='harmony.amenity')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='harmony.project')),
            ],
        ),
    ]
