# Generated by Django 6.0.4 on 2026-04-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('unit_type', models.CharField(choices=[('2bed', '2 Bedroom'), ('3bed', '3 Bedroom')], default='2bed', max_length=10)),
                ('bedrooms', models.PositiveSmallIntegerField(default=2)),
                ('bathrooms', models.PositiveSmallIntegerField(default=2)),
                ('size_sqm', models.CharField(blank=True, max_length=50)),
                ('size_sqft', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image', models.CharField(blank=True, help_text='Static path under static/, e.g. harmony/Harmony_2_bedroom_floor.png', max_length=255)),
                ('floor_plan', models.CharField(blank=True, help_text='Static path under static/ for the floor plan image', max_length=255)),
                ('features', models.TextField(blank=True, help_text='Comma-separated list of features')),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
