# Generated by Django 6.0.4 on 2026-04-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0002_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='floor_plan_file',
            field=models.ImageField(blank=True, null=True, upload_to='units/floor_plans/'),
        ),
        migrations.AddField(
            model_name='unit',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='units/images/'),
        ),
    ]
