# Generated by Django 6.0.4 on 2026-04-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0003_unit_floor_plan_file_unit_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='gallery/images/')),
                ('vimeo_url', models.CharField(blank=True, help_text='Vimeo URL or video id', max_length=255)),
                ('featured', models.BooleanField(default=False, help_text='Show in homepage preview')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
